package com.ajin.pojo;

import java.util.Date;

public class Node {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.id
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    private Integer id;

    private User user;

    @Override
    public String toString() {
        return "Node{" +
                "id=" + id +
                ", user=" + user +
                ", uid=" + uid +
                ", content='" + content + '\'' +
                ", creatime=" + creatime +
                '}';
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.uid
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.content
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.creatime
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    private Date creatime;

    public Node() {
    }

    public Node(Integer id, Integer uid, String content, Date creatime) {
        this.id = id;
        this.uid = uid;
        this.content = content;
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.id
     *
     * @return the value of node.id
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.id
     *
     * @param id the value for node.id
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.uid
     *
     * @return the value of node.uid
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.uid
     *
     * @param uid the value for node.uid
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.content
     *
     * @return the value of node.content
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.content
     *
     * @param content the value for node.content
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.creatime
     *
     * @return the value of node.creatime
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.creatime
     *
     * @param creatime the value for node.creatime
     *
     * @mbggenerated Wed Nov 16 02:40:30 CST 2022
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }
}